### ISSUE TITLE
Bad urls

### ISSUE THREAD

**Issue by mehdichaouch** [randallkanna/awesome-job-list#16]
Firstly, Nice Job 👏 !

I see some bad urls ending with `…`:
* Stackoverflow: http://stackoverflow.com/jobs/remote-developer-jobs…
* Working Nomads: http://workingnomads.co/remote-development-jobs…
* Remoters: http://remoters.net/jobs/software-development…
* Outsourcely: http://outsourcely.com/remote-web-development-jobs…
* Pangian: https://pangian.com/job-travel-remote/…
* JustRemote: https://justremote.co/remote-developer-jobs…

**Comment by randallkanna** [comment]
thank you!
