### ISSUE TITLE
👀 Still maintained ?

### ISSUE THREAD

**Issue by mehdichaouch** [randallkanna/awesome-job-list#21]
I would like to know if this repo is still maintened before opening a new PR in addition to this one https://github.com/randallkanna/awesome-job-list/pull/19.

**Comment by themarolt** [comment]
I guess not :/

**Comment by mehdichaouch** [comment]
> I guess not :/

I confirm ;)

**Comment by randallkanna** [comment]
Still maintained but I generally like to curate the jobs myself as I've been working on this list for over 7 years so if there's a PR that's sitting around, it's generally because I haven't had enough people reach out asking about adding the new job board
